spring.application.name=PMS
spring.datasource.url=jdbc:mysql://localhost:3306/pms
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
cloudinary.cloud-name=insp8a6y
cloudinary.api-key=439841915682665
cloudinary.api-secret=4_gnDML9kCJ7bKj8nPApgwVwofE

jwt.secret=your-super-secret-key-that-is-at-least-32-characters-long
jwt.expiration=86400000
